# This is a basic workflow to help you get started with Actions

name: "1 - [FEAT] Build % PR"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "feature**" ]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  app:
    uses: modeloauto/.github/workflows/feature.yml@v1
    secrets: inherit

